name: dispatch

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/**"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: datsukan/datsukan-blog-comment-ref
          event-type: module-update
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: datsukan/datsukan-blog-comment-post
          event-type: module-update
